# Generated by Django 4.0.4 on 2022-05-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superback', '0002_comentario_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='superback.nota'),
        ),
    ]
